name: "Get Models"
outputs:
  models:
    description: "Models in json format"
runs:
  using: "composite"
  steps:
    - run: node ./.github/actions/get-models/index.js >> $GITHUB_OUTPUT
      shell: bash
