name: "Get Models"
outputs:
  models:
    description: "Models in json format"
runs:
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "npm"
    - run: npm ci
    - run: npm start
