name: "Get Models"
outputs:
  models:
    description: "Models in json format"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "npm"
        cache-dependency-path: ./.github/actions/get-models/package-lock.json
    - run: npm ci
      shell: bash
      working-directory: ./.github/actions/get-models
    - run: npm start
      shell: bash
      working-directory: ./.github/actions/get-models
