name: iter-dir
on: push
jobs:
  get-models:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-models.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: get-models
        run: |
          models=()
          for model in $(ls -d */) ; do
              echo $model
              models+=("\"${model::-1}\"")
          done
          echo "matrix=$(printf '%s\n' \"${models[@]}\" | jq -R . | jq -s .)" >> $GITHUB_OUTPUT
  job2:
    needs: get-models
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get-models.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.models }}
