name: iter-dir
on: push
jobs:
  get-models:
    runs-on: ubuntu-latest
    outputs:
      models: ${{ steps.get-models.outputs.models }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Get Models
        id: get-models
        uses: ./.github/actions/get-models
  job2:
    needs: get-models
    runs-on: ubuntu-latest
    strategy:
      matrix:
        models: ${{ fromJSON(needs.get-models.outputs.models) }}
    steps:
      - run: echo ${{ matrix.models }}
